### ISSUE TITLE
Pan gesture only works from the navigation bar

### ISSUE THREAD

**Issue by dulacp** [KieranLafferty/KLNoteViewController#10]
Sometimes for really simple card controllers it can be great to be able to move/slide them from wherever the user want to.

To be able to close the card controller from the whole `navigationController.view` on not only the `navigationController.navigationBar`.

I'll add again another configuration option, and make it backward compatible of course.

**Comment by KieranLafferty** [comment]
Hey, yes currently it only has the pan gesture assigned to the uinavigationbar of the uinavigationcontoller. I was looking to avoid the case where the pan gesture may interecept non intentional pan gestures making the UIViewcontroller unresponsive to other actions (i.e button presses and text input). I will try to find some time to test this pull request out before merging
